### PR TITLE
Multiple public shares

### LINKED ISSUE #1928: Multiple Share Links
#Multiple share links is a new feature in oC10, that allows to create more than one public link over the same file/folder.

Current behaviour:

- The Android mobile app only supports one public link. 
- The behaviour right now is showing the first one of the public links created on the server side. 
- If the link is edited in the Android app, the name is removed from the link in server side -> https://github.com/owncloud/core/issues/27622
- If the link is removed from Android app, the next one in the list is displayed.

It will require some actions:

- [X] Share activity using full screen instead of dialog style
- [X] Update wording of sections according to last update in iOS
- [X] Replace 'Add user or group' button with (+) button
- [X] Replace switch to on/off public link with (+) button
- [x] Move section with details of public links to new DialogFragment 
- [x] Replace section with details of public link in ShareActivity with list of public shares
- [x] Add icon to delete public share in item list
- [x] Add icon to copy-to-clipboard AND share-with-apps public link in item list
- [x] Add angle icon to edit details in item list
- [x] Add name field to section with details of public link
- [x] For all the things below: ** grant compatibility with server <= 9.x **
- [x] Update domain model and database to support multiple public shares per OCFile
- [x] Update domain model and database to support optional name parameter in OCShares
- [x] Update FileDataStorageManager to retrieve list of public shares for a given file
- [x] Update Get operations to support multiple public links per OCFile
- [x] Update domain model and database to add new property with public link added to OCShare with OC 9.0.0
- [x] Update CreatePublicShareOperation to support multiple public links per OCFile
- [x] Update UpdatePublicShareOperation to support multiple public links per OCFile
- [x] Update RemoveShareOperation to support multiple public links per OCFile, and connect to delete icon
- [x] Connect icon to copy-or-share action
- [x] Connect icon to update existing public share
- [x] Adapt dialog to handle both creation and update of shares correctly
- [x] Handle the different cases when updating the public share password
- [x] Ensure that password is required when server enforces it
- [x] Ensure that expiration date is shown by default when server enforces it
- [x] Enable or disable multiple links support depending on the corresponding capability (see https://github.com/owncloud/core/issues/27622) 
- [x] Hide list of public links and title if public share is disabled by admin
- [x] Connect allow editing permissions switch when creating or updating a folder public share 
- [x] Fix UI for private shares after going to full screen ShareActivity
- [X]  Warning about public links: owncloud/enterprise#1914 
- [X] Warning about public links with message "Anyone with the link has access to the file/folder" https://github.com/owncloud/core/pull/27844/files 
- [x] Change policy to show warning about public links: depending on server capability
- [x] Clean unneeded code of the previous sharing version
- [x] [QA] Design test plan @jesmrec
- [X] [QA] Validate test plan @jesmrec

___

BUGS & IMPROVEMENTS

- [X] (1) Soft keyboard automatically displayed to input link password https://github.com/owncloud/android/issues/1928#issuecomment-299834718 [FIXED]
- [X] (2) Ask for confirmation is case of link removing https://github.com/owncloud/android/issues/1928#issuecomment-299839271 [FIXED] 
- [X] (3) Not allowing to disable password switch if it is forced. https://github.com/owncloud/android/issues/1928#issuecomment-299847474 [FIXED]
- [X] (4) App crashes if remove expiration (default) https://github.com/owncloud/android/issues/1928#issuecomment-299849323 [FIXED]
- [X] (5) Link is saved without expiration although it is forced https://github.com/owncloud/android/issues/1928#issuecomment-299852941 [FIXED]
- [X] (6) Hide link name section when multiple share links are not supported [FIXED]
- [x] Using token as public share name in public shares list makes no sense in servers < 10  https://github.com/owncloud/android/issues/1928#issuecomment-300077521 [WILL NOT BE FIXED]
- [X] (7) Creation of more than one link is not being prevented in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-299857505 [FIXED]
- [X] (8) Edit public links in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-299862239 [FIXED]
- [X] (9) Disabling expiration is not saved https://github.com/owncloud/android/issues/1928#issuecomment-300101852 [OUT OF SCOPE] 
- [X] (10) Error message is improvable https://github.com/owncloud/android/issues/1928#issuecomment-300107439 [FIXED]
- [X] (11) Error messages in landscape make the buttons vanish https://github.com/owncloud/android/issues/1928#issuecomment-300111388 [FIXED] 
- [X] (12) Filename as default https://github.com/owncloud/android/issues/1928#issuecomment-300170065 [FIXED]
- [X] (13) Softkeyboard in servers < 10 https://github.com/owncloud/android/issues/1928#issuecomment-300192697 [FIXED]
- [X] (14) App crashes in landscape in share view after  asking for the passcode https://github.com/owncloud/android/issues/1928#issuecomment-300232970 [FIXED]
- [X] (15) Expiration not set en Galaxy Tab S https://github.com/owncloud/android/issues/1928#issuecomment-300441620 [FIXED]
- [X] (16) Default date to select is today https://github.com/owncloud/android/issues/1928#issuecomment-300520074 [FIXED]
- [X] (17) Autogenerated numbers in links with default name https://github.com/owncloud/android/issues/1928#issuecomment-300707412 [FIXED]
- [X] (18) Users and groups in small screens https://github.com/owncloud/android/issues/1928#issuecomment-300729371 [FIXED]
- [X] (19) Delete PL + Expiration + Create PL = Crash https://github.com/owncloud/android/issues/1928#issuecomment-300760879 [FIXED] 
- [X] (20) Crash rotating in permissions dialog https://github.com/owncloud/android/issues/1928#issuecomment-301011615  [FIXED]
- [X] (21) Scroll in edit link view https://github.com/owncloud/android/issues/1928#issuecomment-301058231 [FIXED]
- [X] (22) Expiration date disappears by rotating https://github.com/owncloud/android/issues/1928#issuecomment-301387117 [FIXED]

### PR DESCRIPTION
**Pull request by davigonz**
Fixes #1928
Requires https://github.com/owncloud/android-library/pull/163

### CODE REVIEW

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java [hunk 1]
```diff
@@ -0,0 +1,580 @@
...
+
+        // Show or hide edit permission section
+        if (isSharedFolder()){
+            getEditPermissionSection(view).setVisibility(View.VISIBLE);
+        } else {
+            getEditPermissionSection(view).setVisibility(View.GONE);
+        }
+
+        // Show default date enforced by the server, if any
+        if (mCapabilities.getFilesSharingPublicExpireDateDays() > 0) {
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: ```mCapabilities```  could not be available yet. If the device is rotated while this dialog is shown, the app crashes, and it's due to ```mCapabilities```  being ```NULL```

Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: Besides, all this block is only meaningful for "create mode", right? I'd rather use an ``` if (!updating) ... else ```  block instead of let this go all the times and later run the ```updating()```  if needed.

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java [hunk 2]
```diff
@@ -0,0 +1,580 @@
...
+        if (updating()) {
+
+            // Set dialog title to edit
+            getDialogTitle(view).setText(R.string.share_via_link_edit_title);
+
+            // Set existing share name
+            getNameValue(view).setText(mPublicShare.getName());
+
+            // Set the edit permissions, if any
+            if (mPublicShare.getPermissions() == CRUD_PERMISSIONS) {
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: This comparison is not safe enough. We need to check if any of the CUD permissions is enabled.

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java [hunk 3]
```diff
@@ -0,0 +1,580 @@
...
+                String publicLinkName = getNameValue(getView()).getText().toString();
+
+                String publicLinkPassword = getPasswordValue(getView()).getText().toString();
+
+                String expirationDate = getExpirationDateValue(getView()).getText().toString();
+
+                long publicLinkExpirationDateMillis = -1;
+
+                // Parse expiration date and convert it to milliseconds
+                if (expirationDate != null) {
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: This is always 'true' (see the warning in Android Studio). The condition can be deleted safely.

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java [hunk 4]
```diff
@@ -0,0 +1,580 @@
...
+        refreshCapabilitiesFromDB();
+    }
+
+    @Override
+    public void onAttach(Activity activity) {
+        super.onAttach(activity);
+        try {
+            mListener = (ShareFragmentListener) activity;
+        } catch (ClassCastException e) {
+            throw new ClassCastException(activity.toString()
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: Should throw ```IllegalStateException``` , or similar.

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java [hunk 5]
```diff
@@ -0,0 +1,580 @@
...
+    }
+
+    /**
+     * Get expiration date imposed by the server, if any
+     */
+    public long getImposedExpirationDate () {
+
+        long imposedExpirationDate = -1;
+
+        if (mCapabilities.getFilesSharingPublicExpireDateEnforced().isTrue()) {
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: I would add a ```NULL``` check for ```mCapabilities``` to this condition.

File: src/com/owncloud/android/ui/fragment/SearchShareesFragment.java [hunk 6]
```diff
@@ -139,6 +141,8 @@ public boolean onQueryTextChange(String newText) {
             }
         });
 
+        view.setMinimumWidth(R.dimen.share_user_groups_width);
```
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/SearchShareesFragment.java]: I'm curious, why did you move this to code? Wasn't working fine with the old declaration in ```res/layout/search_users_groups_layout.xml``` ?

File: src/com/owncloud/android/utils/GetSharesForFileAsyncTask.java [hunk 7]
```diff
@@ -41,12 +41,12 @@
 /**
  * Async Task to get the users and groups which a file is shared with
  */
-public class GetShareWithUsersAsyncTask extends AsyncTask<Object, Void, Pair<RemoteOperation, RemoteOperationResult>> {
+public class GetSharesForFileAsyncTask extends AsyncTask<Object, Void, Pair<RemoteOperation, RemoteOperationResult>> {
```
Comment (davivel) [inline src/com/owncloud/android/utils/GetSharesForFileAsyncTask.java]: We should move this class to the package ```ui.asynctasks```

File: src/com/owncloud/android/ui/helpers/FileOperationsHelper.java [hunk 8]
```diff
@@ -133,24 +133,62 @@ public void openFile(OCFile file) {
...
+
+
     /**
      * Helper method to share a file via a public link. Starts a request to do it in {@link OperationsService}
      *
      * @param file          The file to share.
      * @param password      Optional password to protect the public share.
      */
-    public void shareFileViaLink(OCFile file, String password) {
+    public void shareFileViaLink(OCFile file,
```
Comment (davivel) [inline src/com/owncloud/android/ui/helpers/FileOperationsHelper.java]: We should add comments to the Javadoc of this method for the rest of parameters, as in ```updateShareViaLink```below.

File: src/com/owncloud/android/operations/RemoveShareOperation.java [hunk 9]
```diff
@@ -32,68 +29,62 @@
...
                 Log_OC.d(TAG, "Share id = " + share.getRemoteId() + " deleted");
 
-                if (ShareType.PUBLIC_LINK.equals(mShareType)) {
-                    file.setShareViaLink(false);
-                    file.setPublicLink("");
-                } else if (ShareType.USER.equals(mShareType) || ShareType.GROUP.equals(mShareType)
-                    || ShareType.FEDERATED.equals(mShareType)){
+                ShareType shareType = share.getShareType();
+                if (ShareType.PUBLIC_LINK.equals(shareType)) {
+                    file.setSharedViaLink(false);
```
Comment (davigonz) [inline src/com/owncloud/android/operations/RemoveShareOperation.java]: Done

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java (hunk 1 above)
Comment (davigonz) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: Fixed

File: src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java (hunk 2 above)
Comment (davigonz) [inline src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java]: I've been doing some tests with this and when I enable the "Allow uploads" switch, the server automatically set the share permissions with 15. I use this value to check if the "Allow uploads" switch has been enabled when creating the share to upload.

File: src/com/owncloud/android/ui/fragment/SearchShareesFragment.java (hunk 6 above)
Comment (davigonz) [inline src/com/owncloud/android/ui/fragment/SearchShareesFragment.java]: This dimension was being hardcoded in `res/layout/search_users_groups_layout.xml `before this change and I created a new dimension (`share_user_groups_width`).  Apart from that, the declaration can be moved back to the layout instead of setting it from the Fragment.

**Comment by davigonz** [comment]
@davivel I've made the requested changes, please check them.

File: src/com/owncloud/android/ui/fragment/SearchShareesFragment.java (hunk 6 above)
Comment (davivel) [inline src/com/owncloud/android/ui/fragment/SearchShareesFragment.java]: Good catch 👍

**Comment by davivel** [comment]
Great job, @davigonz. I added a minimum change, take a look.

@jesmrec , this is ready for QA.

cc @michaelstingl @rperezb
