### PR TITLE
Fix uppercase domain bug

### LINKED ISSUE #1852: uppercase letter in server URL results in no connection
[00006805](https://na25.salesforce.com/5003100000ikkcw)

### Actual behaviour
app can't connect to server because of uppercase character in URL

### Expected behaviour
Should connect
 
### Steps to reproduce
1. Try to connect to server with uppercase char in url

### PR DESCRIPTION
**Pull request by ayushpateria**
This fixes #1852. It will automatically convert the subdomain part of the url to lower case.

### CODE REVIEW

File: src/com/owncloud/android/authentication/AuthenticatorActivity.java [hunk 1]
```diff
@@ -1206,6 +1207,30 @@ private String stripIndexPhpOrAppsFiles(String url, EditText mHostUrlInput) {
         return url;
     }
 
+
+    private String subdomainToLower(String url, EditText mHostUrlInput) {
+        if(url.toLowerCase().startsWith("http://") ||
+                url.toLowerCase().startsWith("https://")) {
+            if(url.indexOf("/", 8) != -1)
+                url = url.substring(0, url.indexOf("/", 8)).toLowerCase() + url.substring(url.indexOf("/", 8), url.length());
```
Comment (davivel) [inline src/com/owncloud/android/authentication/AuthenticatorActivity.java]: Please, wrap lines at 120 characters so that they can be read in Github in a glance, without using the horizontal scrollbar.

**Comment by davivel** [comment]
@jesmrec , this can be tested. Thanks.

**Comment by ayushpateria** [comment]
@davivel  Please check again.

**Comment by davivel** [comment]
@ayushpateria , now we need to wait to @jesmrec confirms the behaviour.

Thanks for your help :)

**Comment by jesmrec** [comment]
Approved. Thanks for your contribution @ayushpateria 

CC @davivel @davigonz
