### PR TITLE
Grant that cancellations of tasks generating thumbnails really works …

### LINKED ISSUE #1169: I can't upload the video
### Steps to reproduce
1. Tap 'Upload', select 'From files'ç
2. Browse to camera folder (<public_storage>/DCIM/Camera/) and select the last video in the list
3. Click in Upload, the application says "Wait a moment" . The dialog never vanishes, and I can't upload the video

IMPORTANT: camera folder has 100s of pictures

Maybe related: after a while, the app crashes, with the next log:

´´´
09-21 13:29:14.515  23946-25245/com.owncloud.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 589836 byte allocation with 113524 free bytes and 110KB until OOM"
09-21 13:29:14.555  23946-25245/com.owncloud.android E/ThumbnailsCacheManager﹕ Generation of thumbnail for /storage/emulated/0/DCIM/Camera/IMG_20150823_133829.jpg failed
   java.lang.OutOfMemoryError: Failed to allocate a 589836 byte allocation with 113524 free bytes and 110KB until OOM
           at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
           at android.graphics.Bitmap.nativeCreate(Native Method)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:709)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
           at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:436)
           at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:226)
           at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:201)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.addThumbnailToCache(ThumbnailsCacheManager.java:229)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doFileInBackground(ThumbnailsCacheManager.java:351)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:182)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:143)
           at android.os.AsyncTask$2.call(AsyncTask.java:292)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
´´´

### PR DESCRIPTION
**Pull request by davivel**
…for reused icon views

Fixes #1169

### CODE REVIEW

**Comment by davivel** [comment]
Please, review the code @masensio , @tobiasKaminsky , @AndyScherzinger .

Anybody else may review too.

**Comment by masensio** [comment]
+1

File: src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java [hunk 1]
```diff
@@ -104,6 +107,12 @@ public View getView(int position, View convertView, ViewGroup parent) {
             fileName.setText(name);
             
             ImageView fileIcon = (ImageView) view.findViewById(R.id.thumbnail);
+
+            /** Cancellation needs do be checked and done before changing the drawable in fileIcon, or
+             * {@link ThumbnailsCacheManager#cancelPotentialWork} will NEVER cancel any task.
+             **/
+            boolean allowedToCreateNewThumbnail = (ThumbnailsCacheManager.cancelPotentialWork(file, fileIcon));
```
Comment (AndyScherzinger) [inline src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java]: What is the reason for having this flag in this line? Wouldn't this flag only be needed in the else branch (!directory), so for a directory you wouldn't initialize and calculate the flag, just in the branch for files? :)

File: src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java [hunk 2]
```diff
@@ -157,7 +166,9 @@ public View getView(int position, View convertView, ViewGroup parent) {
                 		        );
                             fileIcon.setImageDrawable(asyncDrawable);
                             task.execute(file);
-                        }
+                            Log_OC.v(TAG, "Executing task to generate a new thumbnail");
```
Comment (AndyScherzinger) [inline src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java]: general question regarding the LOG statements. As for general appliance how about moving the LOG statements into the Task implementation itself so any use of the task would have these statements?

**Comment by AndyScherzinger** [comment]
Looks good to me :+1: Just some minor details questions, maybe wrong due to the lack of a detailed understanding of this part of the code in general :)

File: src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java (hunk 1 above)
Comment (davivel) [inline src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java]: The method ```cancelPotentialWork(...)``` is not just generating the flag, but checking if the imageView 'fileIcon' has a ```ThumbnailGenerationTask``` in progress associated to its contained ```Drawable```, and *cancelling* it in case that it's loading the thumbnail for a file different than the current file.

Case: a thumbnail is started to be generated for a PNG file, the task is associated to the imageView for the thumbnail in the list; the user scrolls up before the thumbnail is ready; the ListAdapter resuses the view of the PNG file for a folder. With this line here, the task is cancelled ; with the line in the !directory branch, the tasks keeps running until saving the thumbnail in the cache. Not functionallly wrong, but with tons of images in the same folder let all the thumbnail tasks finishing results in a performnace problem.

There are other things that could be done to control better the performance in these cases, of course. Consider this patch a minimum effort to control the specific issue pointed, with the target of releasing ASAP.

File: src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java (hunk 2 above)
Comment (davivel) [inline src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java]: Well, depends on what you really want to log. In this case I wanted to have a look on how many tasks were requested and how many were cancelled. Where to put the log in the Task? In doInBackground? Maybe it's not executed if something fails in preExecute(), and if it runs may be "quite later" than the call to 'execute'. 

But I see your point, having logs in the main methods on ```AsyncTasks``` would help in a general case for debugging.

**Comment by AndyScherzinger** [comment]
Thanks for the comments, as I said questions and minor things and I see your points. For releasing ASAP there is nothing I have to brag about :grinning:
