### PR TITLE
Fix and cleanup confirmation dialogs in settings

### LINKED ISSUE #2478: Canceling dialog in settings turns on setting
### Steps to reproduce
1. Open settings
2. Click on "Touches with other visible windows"
3. Cancel the dialog by clicking somewhere outside the dialog
4. Touches with other visible windows is now turned on

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)
This is most likely a client-only issue.

### Environment data
Android version: 7.1.2

Device model: Oneplus X

Stock or customized system: Lineage 14

ownCloud app version: 2.1.0

ownCloud server version: 10

### PR
https://github.com/owncloud/android/pull/2492
https://github.com/owncloud/android/pull/2491

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2478
Closes #2491

### CODE REVIEW

File: owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java [hunk 1]
```diff
@@ -331,32 +331,23 @@ public void onCreate(Bundle savedInstanceState) {
...
-                        }
-
-                        appPrefs.apply();
-
-                        return true;
+                    SharedPreferences.Editor appPrefs = PreferenceManager.
+                            getDefaultSharedPreferences(getApplicationContext()).edit();
+
+                    if ((Boolean) newValue) {
+                        new AlertDialog.Builder(this)
```
Comment (davigonz) [inline owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: Why have you removed the showConfirmationDialog method and decided to create the dialogs directly several times?

**Comment by davigonz** [comment]
Thanks for this contribution @mueller-ma , can you have a look at what I asked above?

File: owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java (hunk 1 above)
Comment (mueller-ma) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: First of all the current implementation of showConfirmationDialog() mis-uses the Builder class.
````
        AlertDialog alertDialog = new AlertDialog.Builder(this).create();
        alertDialog.setTitle(title);
        alertDialog.setMessage(message);
        alertDialog.setButton(DialogInterface.BUTTON_NEGATIVE, getString(R.string.common_no), listener);
        alertDialog.setButton(DialogInterface.BUTTON_POSITIVE, getString(R.string.common_yes), listener);
        alertDialog.show();
````
The intent use of builders is:
````
        AlertDialog alertDialog = new AlertDialog.Builder(this)
        .setTitle(title);
        .setMessage(message);
        .setButton(DialogInterface.BUTTON_NEGATIVE, getString(R.string.common_no), listener);
        .setButton(DialogInterface.BUTTON_POSITIVE, getString(R.string.common_yes), listener);
        .show();
````

After fixing this I realized that showConfirmationDialog() is now a simple wrapper for AlertDialog.Builder() which adds nearly no "static" information, like the strings for the buttons. Thus I inlined the function.
Also IMO it's nice to have two listener for both buttons instead of one listener that has a `if (which == DialogInterface.BUTTON_POSITIVE)...`.

Comment (davigonz) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: > First of all the current implementation of showConfirmationDialog() mis-uses the Builder class.

Yes, good catch

> showConfirmationDialog() is now a simple wrapper for AlertDialog.Builder() which adds nearly no "static" information, like the strings for the buttons. 

The aim of that is to save code and avoid using `setTitle, setMessage` and `setButton` multiple times. Besides, if we wanted to change the title of the buttons at some point, we would just need to do it in a single place.

About using two listeners, you could keep the `showConfirmationDialog` and pass two different listeners to it instead of just one.

Comment (mueller-ma) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: IMO calling the Builder is much easier to read. You instantly know what `setTitle()` does, but you'll have to look at showConfirmationDialog() implementation to know what the third parameter is.

Comment (davigonz) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: > You instantly know what setTitle() does

I think that if we followed this approach, we would never create methods to avoid duplicated code since using constructors or builders directly is always easier to read. 

About the third parameter, maybe creating a listener variable before calling `showConfirmationDialog()` let readers know better what the third parameter is.

IMO, avoiding duplicated code by calling methods which create/build objects is a good practice.

Comment (mueller-ma) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: I understand your arguments, but in this case the duplicate code is `android.R.string.ok` and `android.R.string.ok`.
If you really want to have a `showConfirmationDialog()` function I'll create it anyway.

Comment (davigonz) [reply owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java]: No worries, since you have included a new listener (setOnCancelListener) maybe is too much for `showConfirmationDialog` and your option fits better.

**Comment by jesmrec** [comment]
Approved. Now the option is not toggled till the correct option is tapped. Thanks for the contribution!

**Comment by jesmrec** [comment]
@mueller-ma could you rebase to update the branch?

**Comment by mueller-ma** [comment]
PR rebased

**Comment by jesmrec** [comment]
thanks!! merging...
