### PR TITLE
Potential fix to anr related with camera uploads retries

### LINKED ISSUE #2561: [BUG] Crash triggered by RemoteServiceException (reported in Google Play)
### Actual behaviour
- Crash with no additional information. To be researched.

### Expected behaviour
- No crash

### Steps to reproduce
1. Not defined yet, Google Play report does not show additional details, but there's some people dealing with the same error on StackOverflow. Likely related to the start of foreground services. (https://stackoverflow.com/questions/50131759/remoteserviceexception-error)

### Environment data
Android version: 9 (90% of total reports)

Device model: OnePlus OnePlus6T (OnePlus6T)

ownCloud app version: 2.10.1

ownCloud server version: unknown

#### ownCloud log (data/owncloud.log)
```
android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1804)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6558)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)
```

Possible useful logs: 
```
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{24fee0 u0 com.owncloud.android/.files.services.FileUploader}
```

### PR DESCRIPTION
**Pull request by abelgardep**
It may fix #2561 according to logs.

We have this log:
`Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{24fee0 u0 com.owncloud.android/.files.services.FileUploader}`

This code determines if it is needed to call startForegroundService.
`if ((isCameraUploadFile || isAvailableOfflineFile || isRequestedFromWifiBackEvent) &&
                Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {`

In the retry function, we launch a foreground service but we send only `isRequestedFromWifiBackEvent`. If it is not, `startForegroundService` is not called in the FileUploader.

With this change, we will send how it was created, and if it was created by camera uploads, it will call `startForegroundService`

### CODE REVIEW

**Review by theScrabi — APPROVED** [review]

File: owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java [hunk 1]
```diff
@@ -216,6 +216,8 @@ private void retry(Context context, Account account, OCUpload upload, boolean re
                 // services and camera uploads feature may try to do it, this is the way to proceed
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java:216]: This commend could be updated
`Since in Android 0 the apps running in background are not allowed to start background services.
The camera uploads feature may try to do this. A way to solve this is to run the camera upload feature in the foreground.` This way its more clear what happens here.

**Review by theScrabi — APPROVED** [review]
Could you please exmplain how this may fix the issue described [here](#2561)?

**Comment by abelgardep** [comment]
> Could you please exmplain how this may fix the issue described [here](https://github.com/owncloud/android/issues/2561)?

Sure i posted a explanation in the pr description, sorry.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java (hunk 1 above)
Comment (abelgardep) [reply owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java:218]: It is not related with current PR, but change applied.

**Review by theScrabi — APPROVED** [review]

**Comment by jesmrec** [comment]
No much QA to do here. Internal stuff to protect from ANR. 

Please, move forward to 2.15.3
