### PR TITLE
Fix remote service exception

### LINKED ISSUE #2953: [BUG] Av. offline from scratch
From time to time, i've detected the following error:

```
2020-09-09 17:14:04.648 24091-24091/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 24091
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Steps:

1. Install from scratch
2. Set a file to available offline

Current: app crashes
Expected: available offline

Android 9

Related PR: https://github.com/owncloud/android/pull/2967

### PR DESCRIPTION
**Pull request by abelgardep**
Fixes #2953

### CODE REVIEW

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 1]
```diff
@@ -550,11 +535,24 @@ private void notifyDownloadStart(DownloadFileOperation download) {
...
         showDetailsIntent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
 
-        mNotificationBuilder.setContentIntent(PendingIntent.getActivity(
-                this, (int) System.currentTimeMillis(), showDetailsIntent, 0
-        ));
-
-        getNotificationManager().notify(R.string.downloader_download_in_progress_ticker, mNotificationBuilder.build());
+        /// create status notification with a progress bar
+        mLastPercent = 0;
+        getNotificationBuilder()
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:540]: This could be exported into its own method.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 2]
```diff
@@ -550,11 +535,24 @@ private void notifyDownloadStart(DownloadFileOperation download) {
...
+                .setOngoing(true)
+                .setProgress(100, 0, download.getSize() < 0)
+                .setContentText(
+                        String.format(getString(R.string.downloader_download_in_progress_content), 0,
+                                new File(download.getSavePath()).getName()))
+                .setWhen(System.currentTimeMillis())
+                .setContentIntent(PendingIntent.getActivity(this, (int) System.currentTimeMillis(), showDetailsIntent
+                        , 0));
+
+        getNotificationManager().notify(
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:552]: This could be exported into its own method.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 3]
```diff
@@ -565,12 +563,15 @@ public void onTransferProgress(long progressRate, long totalTransferredSoFar,
                                    long totalToTransfer, String filePath) {
         int percent = (int) (100.0 * ((double) totalTransferredSoFar) / ((double) totalToTransfer));
         if (percent != mLastPercent) {
-            mNotificationBuilder.setProgress(100, percent, totalToTransfer < 0);
             String fileName = filePath.substring(filePath.lastIndexOf(File.separator) + 1);
             String text = String.format(getString(R.string.downloader_download_in_progress_content), percent, fileName);
-            mNotificationBuilder.setContentText(text);
-            getNotificationManager().notify(R.string.downloader_download_in_progress_ticker,
-                    mNotificationBuilder.build());
+            getNotificationBuilder()
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:568]: This could be exported into its own method.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 4]
```diff
@@ -592,7 +593,7 @@ private void notifyDownloadResult(DownloadFileOperation download,
             tickerId = (needsToUpdateCredentials) ?
                     R.string.downloader_download_failed_credentials_error : tickerId;
 
-            mNotificationBuilder
+            getNotificationBuilder()
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:596]: Please export this into it's own method.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 5]
```diff
@@ -611,25 +612,25 @@ private void notifyDownloadResult(DownloadFileOperation download,
...
                 updateAccountCredentials.addFlags(Intent.FLAG_FROM_BACKGROUND);
-                mNotificationBuilder
+                getNotificationBuilder()
                         .setContentIntent(PendingIntent.getActivity(
                                 this, (int) System.currentTimeMillis(), updateAccountCredentials,
                                 PendingIntent.FLAG_ONE_SHOT));
 
             } else {
                 // TODO put something smart in showDetailsIntent
                 Intent showDetailsIntent = new Intent();
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:622]: Same here.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java [hunk 6]
```diff
@@ -611,25 +612,25 @@ private void notifyDownloadResult(DownloadFileOperation download,
...
-                mNotificationBuilder
+                getNotificationBuilder()
                         .setContentIntent(PendingIntent.getActivity(
                                 this, (int) System.currentTimeMillis(), showDetailsIntent, 0));
             }
 
-            mNotificationBuilder.setContentText(
+            getNotificationBuilder().setContentText(
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:628]: Same here.

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java (hunk 1 above)
Comment (abelgardep) [reply owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:540]: Sorry, I don't get what you mean, could you explain it to me?

Comment (theScrabi) [reply owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:540]: the building of the notification consists of many lines of code that belong together. Pleas export the building into its own methode.

File: owncloudApp/src/main/java/com/owncloud/android/utils/NotificationUtils.kt [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+    }
+
+    /**
+     * Show a notification with file conflict information, that will open a dialog to solve it when tapping it
+     *
+     * @param fileInConflict file in conflict
+     * @param account        account which the file in conflict belongs to
+     */
+    @JvmStatic
+    fun notifyConflict(fileInConflict: OCFile, account: Account?, context: Context) {
```
Comment (theScrabi) [inline owncloudApp/src/main/java/com/owncloud/android/utils/NotificationUtils.kt:74]: Please reduce the size of this method by braking it apart into logical smaller pieces.

**Review by theScrabi — CHANGES_REQUESTED** [review]

File: owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java (hunk 1 above)
Comment (abelgardep) [reply owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:540]: I agree that notifications need a rework, but maybe it is not the right moment. I just moved some old code. I don't think that refactor every single file on each PR is the proper way to fix a located problem.

We have a new architecture issue about downloading a file and probably we will refactor or even delete this file.

Comment (theScrabi) [reply owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java:540]: all right.

**Review by theScrabi — APPROVED** [review]

**Comment by jesmrec** [comment]
In terms of the problem, this is fixed on my side. 

Just one consideration, ofter building the current branch with Android Studio, some diffs in the project:

```
diff --git a/.idea/codeStyles/Project.xml b/.idea/codeStyles/Project.xml
index ce6f979..4da31ad 100644
--- a/.idea/codeStyles/Project.xml
+++ b/.idea/codeStyles/Project.xml
@@ -24,16 +24,7 @@
     <JetCodeStyleSettings>
       <option name="PACKAGES_TO_USE_STAR_IMPORTS">
         <value>
-          <package name="kotlinx.android.synthetic" alias="false" withSubpackages="true" />
-        </value>
-      </option>
-      <option name="PACKAGES_IMPORT_LAYOUT">
-        <value>
-          <package name="" alias="false" withSubpackages="true" />
-          <package name="java" alias="false" withSubpackages="true" />
-          <package name="javax" alias="false" withSubpackages="true" />
-          <package name="kotlin" alias="false" withSubpackages="true" />
-          <package name="" alias="true" withSubpackages="true" />
+          <package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
         </value>
       </option>
       <option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="2147483647" />
(END)
```
something to fix there?

**Comment by abelgardep** [comment]
This was merged via https://github.com/owncloud/android/pull/2961

I don't get that code style diff at the moment.

**Comment by jesmrec** [comment]
In any case, this is not a blocker for the current problem, that is fixed and approved.
